### ISSUE TITLE
为什么release出的版本显示都是2015年8月？

### ISSUE THREAD

**Issue by hdstar2009** [Ahref-Group/SS-Panel-smarty-Edition#25]
看http://prpr.cf/?p=1049这里过来的，不是最新起码也是2016年吗

**Comment by kot4ri** [comment]
请直接view code
https://github.com/Ahref-Group/SS-Panel-smarty-Edition?files=1

**Comment by umehina** [comment]
直接看代码即可 </br>
[https://github.com/Ahref-Group/SS-Panel-smarty-Edition/tree/smarty](url)

**Comment by C0lacan** [comment]
2015年8月的是xuanhuan的原版
