### ISSUE TITLE
请问用户暂停时间

### ISSUE THREAD

**Issue by onepve** [Ahref-Group/SS-Panel-smarty-Edition#26]
用户暂停时间是到期后账号自动变成停用状态吗?
那么不启用签到功能的账号,用户暂停时间有效吗?

**Comment by C0lacan** [comment]
自动暂停需要crontab。正常运行并设置生效，默认免费用户到期就会暂停，需要自定义可以改tools/check_plan.php

**Comment by onepve** [comment]
原来在tools里..我竟然忽视了这个文件夹...非常感谢
另外问一下.
会员套餐 A B C D E 分别代表什么类型?

**Comment by C0lacan** [comment]
A-免费用户
B-普通用户
C-普通节点不限流量用户
D-高级用户
E-高级节点不限流量用户

**Comment by onepve** [comment]
您好.我修改了一些地方.然后去生成 兑换码
点击 计划类型 后计划编号哪里无任何选项出来没办法继续....是我哪里搞坏了吗..ORZ
https://github.com/wxliuxh/SS-Panel-smarty-Edition

**Comment by C0lacan** [comment]
进下QQ群我瞅瞅570902149
