### ISSUE TITLE
这个是基于V2的还是V3 还是独立的

### ISSUE THREAD

**Issue by thomas0612** [Ahref-Group/SS-Panel-smarty-Edition#30]
这个是基于V2的还是V3 还是独立的

**Comment by Unixeno** [comment]
不是写了吗，基于V2的修改版
https://github.com/xuanhuan/ss-panel

**Comment by thomas0612** [comment]
出个详细的使用教程吧 = =

**Comment by C0lacan** [comment]
这需要啥详细教程么，具体需要的环境和配置都列出来了

**Comment by thomas0612** [comment]
这个实用的前提是先把V2部署好？然后在V2的基础上应用这个？还是直接上这个就行

**Comment by C0lacan** [comment]
直接部署就行

**Comment by Unixeno** [comment]
直接clone到你本地
导入sql啥的就行了

**Comment by Unixeno** [comment]
这个版本到此为止，除必要的bug修复外不会管了
我们现在在开发全新的panel

**Comment by thomas0612** [comment]
好的    刚接触  不太懂~~~叨扰了

**Comment by thomas0612** [comment]
加油~~~

**Comment by thomas0612** [comment]
等新版本出来赞助你们一波

**Comment by onepve** [comment]
https://github.com/wxliuxh/shadowsocks_install/blob/master/ss-panel/v2改版安装过程.md
