### ISSUE TITLE
兑换码页面loading问题

### ISSUE THREAD

**Issue by FincerDW** [Ahref-Group/SS-Panel-smarty-Edition#37]
不管填写或者不填写兑换码，在提交后都无法提示任何信息，一直在loading

**Comment by kot4ri** [comment]
请确认您的密钥是否符合规则

**Comment by onepve** [comment]
加密支持库安装了没?上个探针看看

**Comment by FincerDW** [comment]
@kot4ri 
![qq 20161105171915](https://cloud.githubusercontent.com/assets/23273094/20029021/26a05856-a37c-11e6-9261-84246568db53.png)
规则是指这里么？
''里面自定义还是说0X0000这个参数不对

**Comment by onepve** [comment]
至少0x0001?

**Comment by FincerDW** [comment]
@wxliuxh 军哥的LNMP环境，应该没问题吧

**Comment by kot4ri** [comment]
请填写生成密钥，八位字符即可

**Comment by onepve** [comment]
需求/Requirements

PHP >= 5.4
PDO Extension
MCrypt Extension
Mysql >= 5.1

你自己上探针看有没有支持呗

**Comment by FincerDW** [comment]
PDO MCrypt都支持的，版本也没问题。

现在主要问题是，就算我不输入兑换码，也是 无限loading。不会出现“无效兑换码，请检查”

**Comment by C0lacan** [comment]
打开console看错误日志，否则不知道问题

**Comment by dawei9264** [comment]
@C0lacan 
![Uploading 20161105174755.png…]()

**Comment by FincerDW** [comment]
@C0lacan 
![Image of Yaktocat](http://ww1.sinaimg.cn/large/0060lm7Tgw1f9hdszu0o9j30xx03yaaq.jpg)

**Comment by kot4ri** [comment]
c0lacan霸霸不要砍我 我错了 我写的bug我自己修

**Comment by Xeonacid** [comment]
@kot4ri 可乐罐写的bug比你多多了（手动滑稽
