### ISSUE TITLE
站点启用https后显示不正常

### ISSUE THREAD

**Issue by ding365** [Ahref-Group/SS-Panel-smarty-Edition#41]
![image](https://cloud.githubusercontent.com/assets/23565068/20907404/f5f5793c-bb88-11e6-914b-c5475246e2d4.png)

**Comment by C0lacan** [comment]
@hinext 确定你在config.php的设置中url地址正确

**Comment by kot4ri** [comment]
请在配置文件中修改地址，http改成https

**Comment by ding365** [comment]
配置中就是htpps。不过现在解重启了一下nginx解决啦. 谢谢各位大大
