### ISSUE TITLE
访问网站500错误

### ISSUE THREAD

**Issue by Awrtiger** [Ahref-Group/SS-Panel-smarty-Edition#43]
环境LAMP
错误日志
[Fri Feb 24 08:41:43.400303 2017] [:error] [pid 13947] [client ] PHP Fatal error:  Uncaught  --> Smarty: unable to write file /var/www/html/templates_c/materialize/wrt58aff1c761a314_12677864 <-- \n  thrown in /var/www/html/lib/Ss/smarty/sysplugins/smarty_internal_write_file.php on line 46
大佬 怎么解决？

**Comment by Xeonacid** [comment]
请保证/templates_c有写权限

**Comment by Awrtiger** [comment]
嗯嗯 修改权限后可以了 谢谢
