### ISSUE TITLE
t

### ISSUE THREAD

**Issue by holyen** [Ahref-Group/SS-Panel-smarty-Edition#45]
Notice: Undefined variable: randomChar in /var/www/html/SS-Panel-smarty-Edition-smarty/index.php on line 10

Notice: Undefined variable: randomChar in /var/www/html/SS-Panel-smarty-Edition-smarty/index.php on line 11

Fatal error: Uncaught --> Smarty: unable to write file /var/www/html/SS-Panel-smarty-Edition-smarty/templates_c/materialize/wrt58dcd3cfbe99e9_04557892 <-- thrown in /var/www/html/SS-Panel-smarty-Edition-smarty/lib/Ss/smarty/sysplugins/smarty_internal_write_file.php on line 46
报了这几个错

**Comment by q3aob4on** [comment]
兄弟 我也是报这几个错 你解决了么?
