### ISSUE TITLE
SQLite3.php

### ISSUE THREAD

**Issue by shom** [Ahref-Group/SS-Panel-smarty-Edition#46]
找不到SQLite3.php文件怎么办？
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/ss-panel/lib/SQLite3.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/ss-panel/lib/do.php on line 39" while reading response header from upstream, client:  server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:",

**Comment by KazamaSion** [comment]
您应该给 php 安装 sqlite。
例如：`apt-get install php5-sqlite3` ，具体安装方法请自行 Google。

**Comment by shom** [comment]
多谢，这么晚神回复

**Comment by KazamaSion** [comment]
@shom 另外我想提醒您，您的 IP 地址暴露了出来。
建议尽快编辑原始信息以去除 IP。
