### ISSUE TITLE
正常搭建后报错  php7.0 nginx1.8

### ISSUE THREAD

**Issue by q3aob4on** [Ahref-Group/SS-Panel-smarty-Edition#49]
Notice: Undefined variable: randomChar in /www/wwwroot/shadowsocks/index.php on line 10
Notice: Undefined variable: randomChar in /www/wwwroot/shadowsocks/index.php on line 11
Notice: Undefined index: index_Announcement in /www/wwwroot/shadowsocks/templates_c/materialize/85bd6758dab4edb528c15f9643ba6aaaf9687cdc_0.file.index.tpl.php on line 66
Notice: Trying to get property of non-object in /www/wwwroot/shadowsocks/templates_c/materialize/85bd6758dab4edb528c15f9643ba6aaaf9687cdc_0.file.index.tpl.php on line 66

**Comment by kot4ri** [comment]
该版本不兼容php7.0

**Comment by q3aob4on** [comment]
切换到php5.6 同样提示错误
Notice: Undefined variable: randomChar in /www/wwwroot/ss/index.php on line 10
Notice: Undefined variable: randomChar in /www/wwwroot/ss/index.php on line 11
Fatal error: Uncaught --> Smarty: unable to write file /www/wwwroot/ss/templates_c/materialize/wrt598efc9077cd32_39550817 <-- thrown in /www/wwwroot/ss/lib/Ss/smarty/sysplugins/smarty_internal_write_file.php on line 46
麻烦您帮忙看一下怎么回事

**Comment by kot4ri** [comment]
/ss/lib/Ss/
请授予该目录777权限

**Comment by q3aob4on** [comment]
不好意思啊 我忘改权限了但是再次打开以后还是这样
Notice: Undefined index: index_Announcement in /www/wwwroot/ss/templates_c/materialize/4f2037aa0c0d5d9f48603570114cf9518cd505b8_0.file.index.tpl.php on line 66

Notice: Trying to get property of non-object in /www/wwwroot/ss/templates_c/materialize/4f2037aa0c0d5d9f48603570114cf9518cd505b8_0.file.index.tpl.php on line 66
跟原来的错误一样

**Comment by kot4ri** [comment]
/templates_c
删掉该目录下的所有文件再试一下
如果还有问题您私聊我的Telegram
@kot4ri

**Comment by q3aob4on** [comment]
我删掉了还是不行。。  我刚把shadowsocks卸载了 现在翻不过去 用telegram得稍等一下。。
